### ISSUE TITLE
LiveTV playback does not have pause/back/fwd controls

### ISSUE THREAD

**Issue by wmarler** [kodi-pvr/pvr.nextpvr#122]
I would consider these to be crucial features for a DVR plugin.

**Comment by emveepee** [comment]
Sure it does this is a setup issue not related to the addon code.  Please post  a support post on the NextPVR forum following the support guideline on the wiki https://github.com/sub3/NextPVR/wiki/get-help

**Comment by wmarler** [comment]
Thanks for the 0-second response time! 
"setup" issue of what -- is it a userspace config, e.g. something I didn't do right?

**Comment by GrahamDLL** [comment]
You are much more likely to get help if you use the NextPVR forum ... https://github.com/sub3/NextPVR/wiki/get-help

**Comment by sub3** [comment]
wmarler, this isn't the best place for general support questions. 

Kodi does give the ability to pause live tv and skip back/forward etc. Whether you can do this depends on the version of kodi, version of nextpvr, and whether you've got timeshift mode enabled in the addon settings. If it's just a matter of not liking Kodi's on-screen controls for these features,  this isn't something NextPVR or the NextPVR addon have any control over, and more of a core kodi issue - you'd need to ask the kodi UI guys about that stuff.  (we're the nextpvr guys, and only really responsible for getting the video stream into kodi)

If you want to discuss it further, post a question on either the Kodi forum at https://forum.kodi.tv/, or the NextPVR forums https://forums.nextpvr.com/.

**Comment by wmarler** [comment]
Hey, I'm sorry, I didn't mean to consider this a "general support question." I was comparing the behavior of the pvr.nextpvr plugin to pvr.mythtv plugin, and I legitimately thought the functionality was missing :-/.

I found https://forum.kodi.tv/showthread.php?tid=341823 and understand what's what now. 

I don't object to closing this issue as-is. However, what if we re-scoped it as a feature request: "Add helptext to the 'Advanced' section of the addon configuration screen to tell people what does what?"

Suggestions for helptext:
Realtime: [Default] Most reliable playback, but playback cannot be paused or skipped forwards/backwards.
Timeshift: Enables pausing and skipping, but ... [I'm not sure what "lose any buffered program" means, exactly; does that mean if you pause, skip forwards 30s and realize you've gone too far, you can't skip back 10s?]
ExtendedTimeshift: Slows down tuning and can cause backend crashes if you flip quickly (less than x seconds per channel) through channels, but enables the most flexibility with pausing / skipping LiveTV, as well as saving the entire stream (from the time the channel was tuned) to Recordings.

**Comment by emveepee** [comment]
The client is pretty dumb and settings API although in Matrix I have done a few things separated v4 and v5 settings and for some options here is one line of help.  This is more a wiki consideration nothing to do with the code so feel free in contributing to the wiki.
