### ISSUE TITLE
Improve state handling in pvr.nextpvr

### ISSUE THREAD

**Issue by emveepee** [kodi-pvr/pvr.nextpvr#136]
In moving from p8 threads to std::thread  the plan is to improve the connections state handling and add possibility of additional login parameters.  Here are some current issues.

1. Improve connect at start.  The initial connection uses  kodi::vfs::OpenFile() which does not indicate tcp state.  
    How to distinguish PVR_CONNECTION_STATE_SERVER_UNREACHABLE as a network issue or bad ip/port which should be a permanent failure.

2. Look at issues here https://forum.kodi.tv/showthread.php?tid=355247  with log here https://paste.kodi.tv/tamuhigugo.kodi.

    -  Kodi does not seem to respect PVR_CONNECTION_STATE_DISCONNECTED.   In log check thread T:9264 after the system resumes but before CPowerManager::OnWake: is called.

3. Improve Android sleep/wake state handling toggling.  Systems sleeps when not active so potentially lots of unnecessary reconnects when credentials remain valid.  

4. Improve logic to re-authenticate after a server goes offline currently depends on server side reconnect

5. Fix Matrix OnWake  loop return test

**Comment by ksooo** [comment]
Regarding https://github.com/kodi-pvr/pvr.nextpvr/blob/Matrix/src/pvrclient-nextpvr.cpp#L185

"Connect" gets called from "CreateInstance" (the addon instance "ctor"). During addon instance creation the addon must not assume that network is ready. This is a bug, sorry. Implementation of "Connect" must trigger the connection *asynchronous* and use connection state change callback whenever the backend connection state changes.

**Comment by emveepee** [comment]
> 
> 
> Regarding https://github.com/kodi-pvr/pvr.nextpvr/blob/Matrix/src/pvrclient-nextpvr.cpp#L185
> 
> "Connect" gets called from "CreateInstance" (the addon instance "ctor"). During addon instance creation the addon must not assume that network is ready. This is a bug, sorry. Implementation of "Connect" must trigger the connection _asynchronous_ and use connection state change callback whenever the backend connection state changes.

Ok thanks so if the user enters an incorrect  bad ip/port that should not be a permanent failure?  This is probably the most common error we get, mitigated a bit in Matrix with auto IP detect.

**Comment by ksooo** [comment]
> so if the user enters an incorrect bad ip/port that should not be a permanent failure?

 No, it shouldn't as the user can fix that anytime, for example in reaction to error notification triggered by the correct connection state change callback from your addon. Permanent error is for something the user can't fix, like API incompatibility of some kind.

**Comment by emveepee** [comment]
> 
> 
> > so if the user enters an incorrect bad ip/port that should not be a permanent failure?
> 
> No, it shouldn't as the user can fix that anytime, for example in reaction to error notification triggered by the correct connection state change callback from your addon. Permanent error is for something the user can't fix, like API incompatibility of some kind.

Ok thanks again.   Do you know if I open/close a raw socket if that helps determine if the network is up?  For #2 the user is already complaining about the notification errors after wake.

**Comment by emveepee** [comment]
I have linked of my  problems with GetBackendVersion() and similar function returning an error when the network was down since Kodi only seem to work properly unless they return PVR_ERROR_NO_ERROR even when it is not true

@ksooo  @phunkyfish I noted this comment in vuplus.  Is that a valid statement?

  // Note: "connecting" must only be set one time, before the very first connection attempt, not on every reconnect.

**Comment by phunkyfish** [comment]
It was probably true at the time I wrote it 😉

Can you link the file that line is from? Sorry, I’m away and only have my phone.

**Comment by emveepee** [comment]
> 
> Can you link the file that line is from? Sorry, I’m away and only have my phone.

https://github.com/kodi-pvr/pvr.vuplus/blob/Matrix/src/enigma2/ConnectionManager.cpp#L40

**Comment by phunkyfish** [comment]
I think assume it’s true unless you find otherwise.

**Comment by emveepee** [comment]
> 
> 
> > so if the user enters an incorrect bad ip/port that should not be a permanent failure?
> 
> No, it shouldn't as the user can fix that anytime, for example in reaction to error notification triggered by the correct connection state change callback from your addon. Permanent error is for something the user can't fix, like API incompatibility of some kind.

@ksooo I am having trouble getting this to work.  If I don't return ADDON_STATUS_OK here, the return here https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/addons/PVRClient.cpp#L164  means_bReadyToUse can never be set true so it acts the same as a Permanent fail that I can't get exit from.  If I do set ADDON_STATUS_OK when I am not ready I get requests for the backend, channels get deleted etc.  Do you feel this is a core issue that I should create?

As a test that this flag impacts things when I set m_bReadyToUse true here https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/addons/PVRClient.cpp#L526 the reconnect happens when I expect.

**Comment by emveepee** [comment]
I have addressed these issues in recent PR's
