### ISSUE TITLE
Remove port requirement and just put URL with no port requirement.

### ISSUE THREAD

**Issue by Empathetic** [kodi-pvr/pvr.nextpvr#212]
The reason why I'm asking for this is because it's currently hardcoded in the addon and it causes issues if you have nextpvr on a custom domain or behind a proxy. Removing the port requirement will make it easier for anyone to use the nextpvr addon on kodi no matter whether they are behind a proxy, custom domain, or just using regular settings. Normal users can just insert the url with the port as nextpvr works via whatever url is set for the nextpvr server anyways. I don't get why the port requirement is even hardcoded in the addon, it should have always been url based. Not trying to be rude, just curious is all. This thread is a perfect example of why this is an issue https://forums.nextpvr.com/showthread.php?tid=61728&page=4

**Comment by Empathetic** [comment]
Just an example on why this is such an issue: if you have a domain like mydomain.com, the addon currently inserts a port after  the domain name so it becomes mydomain.com:8866 when it should just be mydomain.com. It causes the addon to not connect when you have a domain or are behind a proxy that doesn't require you to use a port.

**Comment by phunkyfish** [comment]
Can you not just set the port as 80 and leave the proxy do it’s thing?

**Comment by emveepee** [comment]
Did you try setting port to 0?  I found that this makes curl treat it as if it was not entered and :port is not added to the hostname. 

In settings the port is a separate field to make entry easier.  Most people keep the port and change the IP and doing that in one field that via a remote only is not that easy.  Support would increase and the code changes for a seamless upgrade aren't as easy as you may think.

**Comment by Empathetic** [comment]
> 

Just tried with port 0, it's working as intended now with a custom domain. Apologies, didn't realize adding 0 as the port actually removed the port from the url. Was going by that thread and assumed that adding 0 as the port wouldn't work as others already tried in that thread. Thanks, got it up and working now. Closing issue as it's resolved.

**Comment by emveepee** [comment]
This is why can't assume and ask for logs.  Good luck.
