### ISSUE TITLE
Coverity: CID 118369:  Memory - illegal accesses  (BUFFER_SIZE_WARNING)

### ISSUE THREAD

**Issue by ksooo** [kodi-pvr/pvr.nextpvr#29]
<pre>
** CID 118369:  Memory - illegal accesses  (BUFFER_SIZE_WARNING)
/tools/depends/target/binary-addons/x86_64-linux-gnu/build/pvr.nextpvr/src/pvrclient-nextpvr.cpp: 1099 in cPVRClientNextPVR::GetTimers(ADDON_HANDLE_STRUCT *)()

________________________________________________________________________________________________________
*** CID 118369:  Memory - illegal accesses  (BUFFER_SIZE_WARNING)
/tools/depends/target/binary-addons/x86_64-linux-gnu/build/pvr.nextpvr/src/pvrclient-nextpvr.cpp: 1099 in cPVRClientNextPVR::GetTimers(ADDON_HANDLE_STRUCT *)()
1093               {
1094                 tag.iTimerType = TIMER_REPEATING_KEYWORD;
1095                 tag.startTime = 0;
1096                 tag.endTime = 0;
1097                 tag.bStartAnyTime = true;
1098                 tag.bEndAnyTime = true;
>>>     CID 118369:  Memory - illegal accesses  (BUFFER_SIZE_WARNING)
>>>     Calling strncpy with a maximum size argument of 1024 bytes on destination array "tag.strEpgSearchString" of size 1024 bytes might leave the destination string unterminated.
1099                 strncpy(tag.strEpgSearchString, &advancedRulesText.c_str()[9], sizeof(tag.strEpgSearchString));
1100               }
1101             }
1102     
1103             // days
1104             tag.iWeekdays = PVR_WEEKDAY_ALLDAYS;
</pre>

@sub3 This was introduced by your PR #28. Please fix. The line in question should read

<code>strncpy(tag.strEpgSearchString, &advancedRulesText.c_str()[9], sizeof(tag.strEpgSearchString) - 1);</code>

Thanks.

**Comment by Jalle19** [comment]
Fixed by #30
