### ISSUE TITLE
Create tagged release

### ISSUE THREAD

**Issue by candrews** [kodi-pvr/pvr.nextpvr#53]
Can you please create a release tag (looks like it should be "v3.0.1" based on the contents of https://github.com/kodi-pvr/pvr.nextpvr/blob/master/pvr.nextpvr/addon.xml.in )?

That would really help distributions (in my case, Gentoo) package this add-on.

Thanks!

**Comment by rbalint** [comment]
+ 1 for Debian, and I guess for all the derivatives :-)
