### ISSUE TITLE
Failing build with Leia  nightlies...

### ISSUE THREAD

**Issue by mlburgett** [kodi-pvr/pvr.nextpvr#65]
Is there already a plan to update to the 5.7.0 PVR api?

I'm willing to help, if I can.

**Comment by sub3** [comment]
I was intending to, but haven't found the time yet. Are you a developer? If so, I'd be more than happy to have someone have a go at updating it.

**Comment by mlburgett** [comment]
Hello,  yep, as a matter of fact, I am.  I didn't see this (I thought I as supposed to be notified by email, or I'd have checked more often)

I have a PR up with changes that I've tested on RPi2.   I figured you were short on time with the new NextPVR release just dropping...

**Comment by ksooo** [comment]
Fixed by #66
