### ISSUE TITLE
Add support for PVR_RECORDING.iChannelUid

### ISSUE THREAD

**Issue by ksooo** [kodi-pvr/pvr.nextpvr#85]
Please add support for PVR_RECORDING.iChannelUid. Although PVR Addon API declares this property as optional, some Kodi features cannot work if the channel uid is not given with a recording, namely the "red dot" indicating an in-progress recording in pvr recordings window and recently recorded home screen widget, the right context menu entries for recordings in progess, maybe others.

Unfortunately, there is no reliable fix in Kodi possible without an PVR addon API change (which I plan for Kodi v19, btw.).

Thus, I kindly ask the maintainer of this addon or anybody else with the needed skills to add support for PVR_RECORDING.iChannelUid so we can fix the above mentioned issues for Kodi v18.

Thanks.

**Comment by emveepee** [comment]
I had already added this for my next PR for sub. I hoped to submit it a few days ago but I am struggling to get timeshifted radio working for me  (it is working for users testing it)

**Comment by emveepee** [comment]
This issue can be closed as the changes are in 3.13 of the addon.  The red dots are actually very hepful.  It would be nice to see a matching red dot on the EPG item too.

**Comment by ksooo** [comment]
> It would be nice to see a matching red dot on the EPG item too.

 With other pvr addons (e.g. pvr.hts), there are red dots for epg items. Don't have the details at hand right now, but this could be another issue with pvr.nextpvr (or a skin issue in case you do not use Estuary).

**Comment by emveepee** [comment]
I use Estuary in v18.2 nightlies and I see a right arrow not a red circle in the EPG grid.   The red circle is there in recent recordings and channels.

Martin

**Comment by ksooo** [comment]
Screenshot, please.

**Comment by emveepee** [comment]
Here you go. 

![epg](https://user-images.githubusercontent.com/2148031/54075266-523a5800-426b-11e9-9877-ce85894b152b.jpg)

**Comment by ksooo** [comment]
"Kung Fu Panda" it is? The "right arrow" is a clock, man! LOL.

And you see it, because the timer associated with the epg event does not have PVR_TIMER_STATE_RECORDING set, but state PVR_TIMER_STATE_SCHEDULED. It is up to the addon to announce the state change when recording starts.

**Comment by emveepee** [comment]
Ok there must be a timing issue while the server changes its state from scheduled to recording status, which I can deal with, but after a longer delay when I come back I definitely see an arrow which I guess means recording and not a red circle.  

![arrow](https://user-images.githubusercontent.com/2148031/54076178-764f6680-4276-11e9-9563-83ebf019e3dc.jpg)

**Comment by ksooo** [comment]
The "right arrow" is usually denoted as "playback" symbol. HInestly, I did not understand what you could mean with "rigth arrow" until I saw the screen shot. ;-)

To decide which icon to display, Estuary first evaluates LISTITEM_IS_RECORDING, then LISTITEM_HAS_RECORDING. The former just checks the state of the timer associated with the EPG tag in question. The state is set by the addon. If the LISTITEM_IS_RECORDING is not true, which means the addon has not set the respective state at PVR_TIMER. Consequence is that the red dot will not be displayed. 

As of what you say and the screen shots I would say, the addon does set the recording state at the timer not as long as the recording has not ended, but announces a recording (PVR_RECORDING) early, before the recording has ended. This leads to the "right arrow" icon. This is a bit unusual behavior (compared to other addons), but not necessarily a bug, so to speak as it does not cause any bad side effects, right?

**Comment by emveepee** [comment]
Ok to clarify are recordings not supposed to be flagged as recordings until they are complete?   I can certainly change that if the state still allows them to show as recent recordings for in-progress playback.  

I don't see this as a bug but there is a nuance which confused me before.   I need to use the Play icon as a Recording indicator so if the recording is cancelled and the Play  icon  remained, I wasn't sure if the recording was indeed cancelled.  

Thanks for the input

Martin
